theme: jekyll-theme-tactile
footer-links:
  github: moepi
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /:collection/:name
  - scope:
      type: posts
    values:
      permalink: /:year/:month/:day/:title:output_ext