theme: jekyll-theme-tactile
footer-links:
  github: moepi
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title.html